[package]
name = "odds"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#fantoccini = "0.19.3"
reqwest = "0.12.4"
#scraper = "0.19.0"
tokio = { version = "1.37.0", features = ["full"] }
